# Generated by Django 6.0.3 on 2026-03-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0002_chatsession_unique_active_session_per_lead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="appuser",
            name="azure_oid",
        ),
        migrations.RemoveField(
            model_name="appuser",
            name="microsoft_tenant_id",
        ),
        migrations.AddField(
            model_name="appuser",
            name="oidc_issuer",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Origen del Subject (ej. sts.windows.net o accounts.google.com)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appuser",
            name="oidc_sub",
            field=models.CharField(
                blank=True,
                help_text="Subject ID agnóstico (Entra ID Object ID o Google ID)",
                max_length=255,
                null=True,
                unique=True,
            ),
        ),
    ]
