# Generated by Django 6.0.3 on 2026-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0003_oidc_multi_issuer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
