# Generated by Django 6.0.3 on 2026-04-02 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_chatsession_last_message_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
