# Generated by Django 6.0.3 on 2026-04-02 20:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0008_alter_appuser_oidc_issuer_alter_appuser_oidc_sub_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["tenant", "lead", "is_deleted", "status"],
                name="idx_chatsession_tenant_lead_active",
            ),
        ),
    ]
