# Generated by Django 6.0.3 on 2026-04-04 03:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0011_add_metrics_timestamps"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="chatsession",
            name="unique_active_session_per_lead",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="acquisition_source",
            field=models.CharField(
                blank=True,
                help_text="Fuente de adquisición (ad, referral, organic)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="utm_metadata",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Metadatos UTM del referral (utm_source, utm_medium, etc.)",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOT", "Bot"),
                    ("PENDING_ASSIGNMENT", "Pending Assignment"),
                    ("CON_VENDEDOR", "Con Vendedor"),
                    ("GANADO", "Ganado"),
                    ("PERDIDO", "Perdido"),
                    ("ABANDONO_BOT", "Abandono Bot"),
                ],
                default="BOT",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["tenant", "status", "assigned_at"],
                name="idx_chat_sess_assigned",
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["tenant", "status", "closed_at"], name="idx_chat_sess_closed"
            ),
        ),
        migrations.AddIndex(
            model_name="chatsession",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_chat_sess_created"
            ),
        ),
        migrations.AddConstraint(
            model_name="chatsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    models.Q(
                        ("status__in", ["GANADO", "PERDIDO", "ABANDONO_BOT"]),
                        _negated=True,
                    ),
                    ("is_deleted", False),
                ),
                fields=("tenant", "lead"),
                name="unique_active_session_per_lead",
            ),
        ),
    ]
