# Generated by Django 6.0.3 on 2026-04-06 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_add_acquisition_and_utm_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookRateLimit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wa_id_hash', models.CharField(db_index=True, help_text='SHA-256 hash del WaId para agrupar por remitente', max_length=64)),
                ('window_start', models.DateTimeField(db_index=True, help_text='Inicio de la ventana de rate limit')),
                ('request_count', models.IntegerField(default=1, help_text='Cantidad de requests en la ventana actual')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_rate_limits', to='crm.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'wa_id_hash', 'window_start'], name='crm_webhook_tenant__a5d22e_idx')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'wa_id_hash', 'window_start'), name='unique_rate_limit_per_window')],
            },
        ),
    ]
