# Generated by Django 6.0.3 on 2026-04-06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0013_add_webhook_rate_limit"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["tenant", "created_at"], name="idx_auditlog_tenant_created"
            ),
        ),
    ]
