# Generated by Django 6.0.3 on 2026-04-10 04:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0014_add_auditlog_created_at_index"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="auditlog",
            name="idx_auditlog_tenant_created",
        ),
    ]
