# Generated by Django 6.0.3 on 2026-04-13 02:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0015_remove_auditlog_idx_auditlog_tenant_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="salesperson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_sessions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Vendedor",
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOT", "Bot"),
                    ("PENDING_ASSIGNMENT", "Pending Assignment"),
                    ("CON_VENDEDOR", "Con Vendedor"),
                    ("GANADO", "Ganado"),
                    ("PERDIDO", "Perdido"),
                    ("ABANDONO_BOT", "Abandono Bot"),
                ],
                default="BOT",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Nombre"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="nombre_legal",
            field=models.CharField(max_length=255, verbose_name="Nombre legal"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone_number_id",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Phone Number ID"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="routing_mode",
            field=models.CharField(
                choices=[("MANUAL", "Manual"), ("AUTO", "Auto")],
                default="MANUAL",
                max_length=10,
                verbose_name="Modo de enrutamiento",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="rut_empresa",
            field=models.CharField(
                max_length=50, unique=True, verbose_name="RUT empresa"
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="waba_id",
            field=models.CharField(
                db_index=True, max_length=100, unique=True, verbose_name="WABA ID"
            ),
        ),
    ]
