# Generated by Django 6.0.3 on 2026-04-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_alter_chatsession_salesperson_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='pending_assignment_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp cuando el lead completó el FSM y quedó en PENDING_ASSIGNMENT', null=True),
        ),
    ]
