# Generated by Django 6.0.3 on 2026-05-12 03:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crm", "0019_rotate_wa_id_encryption"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="leadnamehistory",
            index=models.Index(
                fields=["lead", "-changed_at"], name="idx_leadhist_lead_changed"
            ),
        ),
    ]
